BET KANU/Controllers/MangerController.cs
using BetKanu.Models;
using BetKanu.Models.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using BET_KANU.Services;
using BET_KANU.ViewModels;
using BetKanu.Models.Common;

namespace BET_KANU.Controllers
{
    [Authorize]
    public class MangerController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IBlobStorageService _blobStorage;

        public MangerController(IUnitOfWork unitOfWork, IBlobStorageService blobStorage)
        {
            _unitOfWork = unitOfWork;
            _blobStorage = blobStorage;
        }

        public ActionResult Index(string Select)
        {
            var vm = new ProductVM()
            {
                products = _unitOfWork.manger.GetAll(Select),
                episode = _unitOfWork.product.GetEpisode(),
                Shops = _unitOfWork.Shop.GetAll()
            };
            return View(vm);
        }

        [HttpGet]
        public ActionResult CreateSong()
        {
            return View(new Product());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateSong([Bind("Title,SmallImage,CoverImage,SmallUrl,CoverUrl,Category,SubCategory,TargetAudince,ReleaseDate,ShortDescription,LongDescription,ScriptE,ScriptW,CreditsE,CreditsW,Wpdf,Epdf,VideoE,VideoW,ViewsE,ViewsW,WestreanPdfFile,EasternPdfFile,IsRelease,MalouliScript,EnglishScript,CreditsM,VideoM,ViewsM,MalouliPdfFile")] Product song)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (song.SmallUrl != null)
                    {
                        string ImagePath = await SaveImage(song.SmallUrl);
                        song.SmallImage = ImagePath;
                    }
                    if (song.CoverUrl != null)
                    {
                        string ImagePath = await SaveImage(song.CoverUrl);
                        song.CoverImage = ImagePath;
                    }
                    if (song.WestreanPdfFile != null)
                    {
                        string filename = await SaveFile(song.WestreanPdfFile);
                        song.Wpdf = filename;
                    }
                    if (song.EasternPdfFile != null)
                    {
                        string filename = await SaveFile(song.EasternPdfFile);
                        song.Epdf = filename;
                    }
                    if (song.MalouliPdfFile != null)
                    {
                        string filename = await SaveFile(song.MalouliPdfFile);
                        song.Mpdf = filename;
                    }
                    song.Category = Category.Songs;
                    var result = _unitOfWork.manger.Add(song);
                    if (result > 0)
                    {
                        TempData["Messagee"] = song.Title + " " + "has been created successfully!";
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (Exception)
                {
                }
            }
            return View(song);
        }

        [HttpGet]
        public ActionResult CreateBook()
        {
            return View(new Product());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateBook([Bind("Title,SmallImage,CoverImage,SmallUrl,CoverUrl,Category,SubCategory,TargetAudince,ReleaseDate,ShortDescription,LongDescription,ScriptE,ScriptW,CreditsE,CreditsW,Author,DesignedBy,Features,ProductBy,Created,Link3,SongsList,Info1,EastrenImageFile,WestreanImageFile,imgUrl3,imgUrl4,imgUrl5,img1,img2,img3,img4,img5,IsRelease")] Product Book)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (Book.SmallUrl != null)
                    {
                        string ImagePath = await SaveImage(Book.SmallUrl);
                        Book.SmallImage = ImagePath;
                    }
                    if (Book.CoverUrl != null)
                    {
                        string ImagePath = await SaveImage(Book.CoverUrl);
                        Book.CoverImage = ImagePath;
                    }
                    if (Book.imgUrl != null)
                    {
                        string ImagePath = await SaveImage(Book.imgUrl);
                        Book.img1 = ImagePath;
                    }
                    if (Book.imgUrl2 != null)
                    {
                        string ImagePath = await SaveImage(Book.imgUrl2);
                        Book.img2 = ImagePath;
                    }
                    if (Book.imgUrl3 != null)
                    {
                        string ImagePath = await SaveImage(Book.imgUrl3);
                        Book.img3 = ImagePath;
                    }
                    if (Book.imgUrl4 != null)
                    {
                        string ImagePath = await SaveImage(Book.imgUrl4);
                        Book.img4 = ImagePath;
                    }
                    if (Book.imgUrl5 != null)
                    {
                        string ImagePath = await SaveImage(Book.imgUrl5);
                        Book.img5 = ImagePath;
                    }
                    Book.Category = Category.Books;
                    var result = _unitOfWork.manger.Add(Book);
                    if (result > 0)
                    {
                        TempData["Messagee"] = Book.Title + " " + "has been created successfully!";
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (Exception)
                {
                    TempData["AlertMessage"] = "Ooops something went wrong !!";
                    return View(Book);
                }
            }
            return View(Book);
        }

        [HttpGet]
        public ActionResult CreateSoftware()
        {
            return View(new Product());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateSoftware([Bind("Title,SmallImage,CoverImage,SmallUrl,CoverUrl,Category,SubCategory,TargetAudince,ReleaseDate,ShortDescription,LongDescription,CreditsE,CreditsW,Source,SponsoredBY,Link1,Link2,Features,ProductBy,Created,Link3,SongsList,Info1,Info2,Info3,EastrenImageFile,WestreanImageFile,imgUrl,imgUrl2,imgUrl3,imgUrl4,imgUrl5,img1,img2,img3,img4,img5,IsRelease")] Product soft)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (soft.SmallUrl != null)
                    {
                        string ImagePath = await SaveImage(soft.SmallUrl);
                        soft.SmallImage = ImagePath;
                    }
                    if (soft.CoverUrl != null)
                    {
                        string ImagePath = await SaveImage(soft.CoverUrl);
                        soft.CoverImage = ImagePath;
                    }
                    if (soft.imgUrl != null)
                    {
                        string ImagePath = await SaveImage(soft.imgUrl);
                        soft.img1 = ImagePath;
                    }
                    if (soft.imgUrl2 != null)
                    {
                        string ImagePath = await SaveImage(soft.imgUrl2);
                        soft.img2 = ImagePath;
                    }
                    if (soft.imgUrl3 != null)
                    {
                        string ImagePath = await SaveImage(soft.imgUrl3);
                        soft.img3 = ImagePath;
                    }
                    if (soft.imgUrl4 != null)
                    {
                        string ImagePath = await SaveImage(soft.imgUrl4);
                        soft.img4 = ImagePath;
                    }
                    if (soft.imgUrl5 != null)
                    {
                        string ImagePath = await SaveImage(soft.imgUrl5);
                        soft.img5 = ImagePath;
                    }
                    soft.Category = Category.Software;
                    var result = _unitOfWork.manger.Add(soft);
                    if (result > 0)
                    {
                        TempData["Messagee"] = soft.Title + " " + "has been created successfully!";
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (Exception)
                {
                    TempData["AlertMessage"] = "Ooops something went wrong !!";
                    return View(soft);
                }
            }
            return View(soft);
        }

        [HttpGet]
        public ActionResult CreateCollection()
        {
            return View(new Product());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateCollection([Bind("Title,SmallImage,CoverImage,SmallUrl,CoverUrl,Category,SubCategory,TargetAudince,ReleaseDate,ShortDescription,LongDescription,ScriptE,ScriptW,imgUrl,imgUrl2,Wpdf,Epdf,VideoE,VideoW,WestreanPdfFile,EasternPdfFile,IsRelease")] Product Collection)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (Collection.SmallUrl != null)
                    {
                        string ImagePath = await SaveImage(Collection.SmallUrl);
                        Collection.SmallImage = ImagePath;
                    }
                    if (Collection.CoverUrl != null)
                    {
                        string ImagePath = await SaveImage(Collection.CoverUrl);
                        Collection.CoverImage = ImagePath;
                    }

BET KANU/Views/Cartoon/CreateCartoonSeries.cshtml
@model Product
<!-- file Uploads -->
<link href="~/plugins/fileuploads/css/dropify.css" rel="stylesheet" type="text/css" />

<link rel="stylesheet" href="~/css/dashboard.css">


@{
    ViewBag.Title = "Create New Product";
}

<div id="wrapper">
    <section class="bg-grey-500 promo">
        <div class="container">
            <h1 style="color:white"> &nbsp;Create New Cartoon-Series </h1>
        </div>
    </section>

    <section>
        <div class="col-md-12">

            <div class="container">
                <div class="col-12">
                    <form class="card" asp-action="CreateCartoonSeries" enctype="multipart/form-data" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-3 col-sm-12">
                                    <div class="form-group">
                                        <label asp-for="Title" class="control-label"></label>
                                        <input asp-for="Title" class="form-control" required />
                                        <span asp-validation-for="Title" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="TargetAudince" class="control-label"></label>
                                        <select class="form-control custom-select" asp-for="TargetAudince" asp-items="Html.GetEnumSelectList<Target>()">
                                            <option selected="selected">-None-</option>
                                        </select>
                                        <span asp-validation-for="TargetAudince" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-12">
                                    <div class="form-group">
                                        <label asp-for="SmallImage" class="control-label"></label>
                                        <input asp-for="SmallUrl" class="dropify form-control" />
                                        <span asp-validation-for="SmallUrl" class="text-danger"></span>
                                    </div>
                                </div>
                          @*      <div class="col-lg-3 col-sm-12">
                                    <div class="form-group">
                                        <label asp-for="CoverImage" class="control-label"></label>
                                        <input asp-for="CoverUrl" class="dropify form-control" />
                                        <span asp-validation-for="CoverUrl" class="text-danger"></span>
                                    </div>
                                </div>*@
                            </div>
                        </div>
                        <div class="card-body" style="color:white">
                            <div class="row">
                                <div class="card">
                                    <div class="card-header">
                                        <h3 class="card-title"> Details</h3>
                                    </div>

                                    <!--START table-responsive -->
                                    <div class="table-responsive">
                                        <table class="table table-striped table-bordered" style="width:100%">
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <label asp-for="SubCategory" class="control-label"></label>
                                                    </td>
                                                    <td>
                                                        <input asp-for="SubCategory" class="form-control" />
                                                        <span asp-validation-for="SubCategory" class="text-danger"></span>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <label asp-for="ReleaseDate" class="control-label"></label>
                                                    </td>
                                                    <td>
                                                        <input asp-for="ReleaseDate" class="form-control" />
                                                        <span asp-validation-for="ReleaseDate" class="text-danger"></span>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <label asp-for="LongDescription" class="control-label"></label>
                                                    </td>
                                                    <td>
                                                        <input asp-for="LongDescription" class="form-control" />
                                                        <span asp-validation-for="LongDescription" class="text-danger"></span>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <label asp-for="ShortDescription" class="control-label"></label>
                                                    </td>
                                                    <td>
                                                        <input asp-for="ShortDescription" class="form-control" />
                                                        <span asp-validation-for="ShortDescription" class="text-danger"></span>
                                                    </td>
                                                </tr>


                                                <tr>
                                                    <td>
                                                        <label asp-for="VideoW" class="control-label"></label>
                                                    </td>
                                                    <td>
                                                        <input asp-for="VideoW" class="form-control" />
                                                        <span asp-validation-for="VideoW" class="text-danger"></span>
                                                    </td>
                                                </tr>
                                                         <tr>
                                                    <td>
                                                        <label asp-for="VideoE" class="control-label"></label>
                                                    </td>
                                                    <td>
                                                        <input asp-for="VideoE" class="form-control" />
                                                        <span asp-validation-for="VideoE" class="text-danger"></span>
                                                    </td>
                                                </tr>
                                                         <tr>
                                                    <td>
                                                        <label asp-for="ViewsW" class="control-label"></label>
                                                    </td>
                                                    <td>
                                                        <input asp-for="ViewsW" class="form-control" />
                                                        <span asp-validation-for="ViewsW" class="text-danger"></span>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <label asp-for="ViewsE" class="control-label"></label>
                                                    </td>
                                                    <td>
                                                        <input asp-for="ViewsE" class="form-control" />
                                                        <span asp-validation-for="ViewsE" class="text-danger"></span>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <!--END table-responsive #3a4258-->

                                </div>
                            </div>
                                          <div class="row text-center">
                                    <div class="col-md-6">
                                    <a asp-action="Index" asp-controller="Manger" class="btn btn-Create btn-shadow w-50">Back to List</a>
                                    </div>
                                 
                                    <div class="col-md-6">
                                        <input type="submit" value="save" class="btn btn-Create btn-shadow w-50" />
                                    </div>
                                </div>
                        </div>
                    </form>
                </div>

            </div>



        </div>
    </section>
</div>



@section Scripts {
    @{
        <!-- file uploads js -->
        <script src="~/plugins/fileuploads/js/dropify.js"></script>
        <script>
            $('.dropify').dropify({
                messages: {
                    'default': 'Drag and drop a file here or click',
                    'replace': 'Drag and drop or click to replace',
                    'remove': 'Remove',
                    'error': 'Ooops, something wrong appended.'
                },
                error: {
                    'fileSize': 'The file size is too big (2M max).'
                }
            });
        </script>

        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

BET KANU/Views/Cartoon/CreateEpisode.cshtml
@model ProductEpisode
<link href="~/plugins/fileuploads/css/dropify.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="~/css/dashboard.css">
@{
    ViewData["Title"] = "CreateEpisodee";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<head>


</head>


<div id="wrapper">
    <section class="bg-grey-500 promo">
        <div class="container">
            <h1 style="color:white"> &nbsp;Create New Episodee</h1>
        </div>
    </section>

    <section>
        <div class="col-md-12">
            <form class="card" asp-action="CreateEpisode" enctype="multipart/form-data" method="post">
                <input type="hidden" asp-for="ProductId" name="ProductId" value="@ViewBag.ProductId" />
                <div class="container">
                    <div class="col-12">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-3 col-sm-12">

                                    <div class="form-group">
                                        <label asp-for="Title" class="control-label"></label>
                                        <input asp-for="Title" name="Title" class="form-control" required />
                                        <span asp-validation-for="Title" class="text-danger"></span>
                                    </div>

                                </div>
                         @*       <div class="col-lg-3 col-sm-12">
                                    <div class="form-group">
                                        <label asp-for="ImageE" class="control-label"></label>
                                        <input asp-for="EastrenImageFile" name="EastrenImageFile" class="dropify form-control" />
                                        <span asp-validation-for="ImageE" class="text-danger"></span>
                                    </div>

                                </div>
                                <div class="col-lg-3 col-sm-12">
                                    <div class="form-group">
                                        <label asp-for="ImageW" class="control-label"></label>
                                        <input asp-for="WestreanImageFile" name="WestreanImageFile" class="dropify form-control" />
                                        <span asp-validation-for="ImageW" class="text-danger"></span>
                                    </div>
                                </div>*@
                            </div>
                        </div>
                        <div class="card-body" style="color:white">
                            <div class="row">
                                <div class="card">
                                    <div class="card-header">
                                        <h3 class="card-title"> Details</h3>
                                    </div>

                                    <!--START table-responsive -->
                                    <div class="table-responsive">
                                        <table class="table table-striped table-bordered" style="width:100%">
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <label asp-for="Views" class="control-label"></label>
                                                    </td>
                                                    <td>
                                                        <div class="form-group">

                                                            <input asp-for="Views" name="Views" class="form-control" />
                                                            <span asp-validation-for="Views" class="text-danger"></span>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <label asp-for="ReleaseDate" class="control-label"></label>
                                                    </td>
                                                    <td>
                                                        <div class="form-group">

                                                            <input asp-for="ReleaseDate" name="ReleaseDate" class="form-control" />
                                                            <span asp-validation-for="ReleaseDate" class="text-danger"></span>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <label asp-for="Status" class="control-label"></label>
                                                    </td>
                                                    <td>
                                                        <select class="form-control custom-select" asp-for="Status" name="Status" asp-items="Html.GetEnumSelectList<Language>()">
                                                            <option selected="selected">-None-</option>
                                                        </select>
                                                        <span asp-validation-for="Status" class="text-danger"></span>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <label asp-for="ProductId" class="control-label"></label>
                                                        <input type="hidden" name="parentId" value="@ViewBag.ProductId" />
                                                    </td>
                                                    <td>
                                                        @*<select asp-for="ProductId" class="form-control" asp-items="@ViewBag.ProductId"></select>*@
                                                        @ViewBag.parentname
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <label asp-for="VideoW" class="control-label"></label>
                                                    </td>
                                                    <td>

                                                        <input asp-for="VideoW" name="VideoW" class="form-control" />
                                                        <span asp-validation-for="VideoW" class="text-danger"></span>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <label asp-for="VideoE" class="control-label"></label>
                                                    </td>
                                                    <td>


                                                        <input asp-for="VideoE" name="VideoE" class="form-control" />
                                                        <span asp-validation-for="VideoE" class="text-danger"></span>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <!--END table-responsive -->
                                </div>
                            </div>
                            <div class="row text-center">
                                <div class="col-md-6">
                                    <a asp-action="EditCartoonSeries" asp-route-id="@ViewBag.ProductId" class="btn btn-Create btn-shadow w-50">Back to List</a>
                                </div>

                                <div class="col-md-6">
                                    <input type="submit" value="save" class="btn btn-Create btn-shadow w-50" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
</div>



@section Scripts {
    @{
        <!-- file uploads js #8f98c1-->
        <script src="~/plugins/fileuploads/js/dropify.js"></script>
        <script>
            $('.dropify').dropify({
                messages: {
                    'default': 'Drag and drop a file here or click',
                    'replace': 'Drag and drop or click to replace',
                    'remove': 'Remove',
                    'error': 'Ooops, something wrong appended.'
                },
                error: {
                    'fileSize': 'The file size is too big (2M max).'
                }
            });
        </script>

        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }